"""OnePoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tn4D0wJf9J2he2gdAH6UmFfnKh9AvIuv
"""

from math import e
from math import sqrt
import sympy as sy
formula = "" # 2-(1/(e**(-x/4)))
error_list = []

def compute(formula, **kwargs):
    expr = sy.sympify(formula)
    return expr.evalf(subs=kwargs)

def func(x):
    return compute(x=x,formula=formula)

def main(x0=0.0, Ep=0.00001):
    # xL = input(print('enter XL : '))
    # xL = float(xL)
    # xR = input(print('enter XR : '))
    # xR = float(xR)
    # Ep = input(print('enter Epsilon : '))
    Ep = float(Ep)
    # x0 = input(print('enter X0 : '))
    x0 = float(x0)

    i = 0
    while(True):
        x_Sum = float(func(x0))
        Ec = abs((x_Sum-x0)/x_Sum)
        i = i + 1
        if (Ec < Ep):
            # print('-----Finish-----')
            # print('Iteration : ', i)
            # print('Error : ', Ec)
            error_list.append(Ec)
            # print('x_Sum : ', x_Sum)
            # print('-----Finish-----')
            break
        else:
            # print('Iteration : ', i)
            # print('Error : ', Ec)
            error_list.append(Ec)
            # print('x_Sum : ', x_Sum)
            x0 = x_Sum